// <auto-generated />
using System;
using FSA_3S.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSA_3S.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSA_3S.Models.Entities.AppointmentEntity", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appointmentDate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterUserId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UpdaterUserId");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ContractEntity", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contractId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contractstatus");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contracttype");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("enddate");

                    b.Property<int?>("RealEstateId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startdate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedat");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterUserId")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RealEstateId");

                    b.HasIndex("UpdaterUserId");

                    b.ToTable("contract");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address");

                    b.Property<string>("CCCD")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("cccd");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdat");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("customertype");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("phonenumber");

                    b.HasKey("CustomerId");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingRealEstateCustomerEntity", b =>
                {
                    b.Property<int>("MappingRealEstateCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mappingRealEstateCustomerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingRealEstateCustomerId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Likes")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("likes");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("MappingRealEstateCustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("mappingrealestatecustomer");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserAppointmentEntity", b =>
                {
                    b.Property<int>("MappingUserAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mappingUserAppointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingUserAppointmentId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MappingUserAppointmentId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("mappinguserappointment");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserNotificationEntity", b =>
                {
                    b.Property<int>("MappingUserNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mappingUserNotificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingUserNotificationId"));

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MappingUserNotificationId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("mappingusernotification");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.NotificationEntity", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("notificationType");

                    b.Property<string>("RelatedId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("relatedId");

                    b.HasKey("NotificationId");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.RealEstateEntity", b =>
                {
                    b.Property<int>("RealEstateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("realEstateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RealEstateId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int")
                        .HasColumnName("bathrooms");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("bedrooms");

                    b.Property<DateOnly?>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type");

                    b.Property<DateOnly?>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updatedat");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UpdaterUserId")
                        .HasColumnType("int");

                    b.HasKey("RealEstateId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("UpdaterUserId");

                    b.ToTable("realestate");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ReportEntity", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reportId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("NumberOfAppointments")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfContracts")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfRealEstates")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.ToTable("report");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthdate");

                    b.Property<string>("CCCD")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("cccd");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("TimeOfWork")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("timeofwork");

                    b.Property<string>("TypeOfStaff")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("typeofstaff");

                    b.HasKey("UserId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.AppointmentEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany("AppointmentsCreated")
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("FSA_3S.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany("AppointmentsUpdated")
                        .HasForeignKey("UpdaterUserId");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.ContractEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany("ContractsCreated")
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("FSA_3S.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId");

                    b.HasOne("FSA_3S.Models.Entities.RealEstateEntity", "RealEstate")
                        .WithMany("Contracts")
                        .HasForeignKey("RealEstateId");

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany("ContractsUpdated")
                        .HasForeignKey("UpdaterUserId");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("RealEstate");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingRealEstateCustomerEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("MappingRealEstateCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.RealEstateEntity", "Property")
                        .WithMany("MappingRealEstateCustomers")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserAppointmentEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.AppointmentEntity", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "User")
                        .WithMany("MappingUserAppointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.MappingUserNotificationEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.NotificationEntity", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "User")
                        .WithMany("MappingUserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.RealEstateEntity", b =>
                {
                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Creator")
                        .WithMany("RealEstatesCreated")
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("FSA_3S.Models.Entities.UserEntity", "Updater")
                        .WithMany("RealEstatesUpdated")
                        .HasForeignKey("UpdaterUserId");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Contracts");

                    b.Navigation("MappingRealEstateCustomers");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.RealEstateEntity", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("MappingRealEstateCustomers");
                });

            modelBuilder.Entity("FSA_3S.Models.Entities.UserEntity", b =>
                {
                    b.Navigation("AppointmentsCreated");

                    b.Navigation("AppointmentsUpdated");

                    b.Navigation("ContractsCreated");

                    b.Navigation("ContractsUpdated");

                    b.Navigation("MappingUserAppointments");

                    b.Navigation("MappingUserNotifications");

                    b.Navigation("RealEstatesCreated");

                    b.Navigation("RealEstatesUpdated");
                });
#pragma warning restore 612, 618
        }
    }
}
